#line 1 "src/lex.yy.cc"

#line 3 "src/lex.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 140
#define YY_END_OF_BUFFER 141
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[448] =
    {   0,
        0,    0,    0,    0,    0,    0,  141,  139,   12,   11,
       13,   89,  139,  113,   74,   97,  139,  103,  104,   72,
       70,  102,   71,  137,   73,  128,  128,  111,  101,   85,
       80,   86,  112,  135,  135,  107,  108,   99,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  105,   98,  106,
      100,   12,  113,    5,    2,    6,    5,    5,  140,   12,
       82,    0,  114,  131,    0,   79,   87,   94,    0,  115,
      132,    0,   77,   68,   75,   69,   76,  109,    0,  129,
        0,    8,    9,   78,  129,  124,  122,  138,  138,  119,

      128,  128,  138,  128,  110,   92,   83,   81,   84,   93,
      135,    0,    0,   96,  135,  135,  135,  135,  135,  135,
      135,  135,   21,  135,  135,  135,  135,  135,  135,  135,
      135,   29,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,   95,   88,   12,    0,    0,    0,
        0,    5,    2,    5,    5,    0,  134,    0,  136,  119,
      129,    0,  116,    8,    0,    9,  129,  124,  124,  122,
      122,  119,  122,  122,  138,  125,  121,  118,  117,  118,
      126,  118,  128,  128,  128,  123,  120,   90,   91,  135,

      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,   26,  135,  135,  135,  135,
       31,  135,  135,   50,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,    0,
        0,    4,    3,  133,  126,   10,  124,  124,  124,  122,
      122,  118,  122,  122,  122,  121,  121,  121,  118,  118,
      118,  127,  118,  128,  128,  120,  120,  120,   58,   14,
      135,  135,   16,   17,  135,  135,  135,  135,  135,  135,
       23,   56,  135,  135,  135,   67,  135,   28,  135,   33,

      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,   61,  130,
      135,  135,  135,  135,   47,  135,  135,    0,    0,  127,
      124,  124,  122,  118,  122,  122,  121,  121,  121,  118,
      120,  120,  120,   15,  135,   49,   18,  135,  135,  135,
      135,  135,   25,  135,  135,    0,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,   63,   37,  135,  135,
      135,  135,  135,  135,  135,  135,   57,  135,   55,  135,
       48,    0,    0,  121,  121,  120,  120,   65,  135,  135,
       51,   22,   24,   27,   30,    0,   64,  135,  135,   62,

      135,  135,   52,  135,  135,   36,   38,   39,   40,   41,
       42,  135,  135,  135,  135,  135,    0,    0,  135,   20,
        0,   34,  135,   53,  135,   66,  135,  135,   45,  135,
      135,  135,    7,    0,   19,    0,   35,  135,   59,   43,
       44,   46,   60,    1,   32,   54,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   23,   24,   25,   26,
       27,   28,   29,    1,   30,   31,   30,   30,   32,   33,
       34,   34,   34,   34,   34,   35,   34,   34,   34,   34,
       34,   34,   34,   34,   36,   34,   34,   37,   34,   34,
       38,   39,   40,   41,   34,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   34,   51,   52,   53,   54,
       55,   56,   34,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    2,    3,    4,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    2,    1,    5,    1,    6,    6,
        6,    6,    6,    1,    2,    1,    1,    1,    1,    6,
        6,    6,    6,    6,    6,    6,    6,    1,    1,    2,
        1,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    1,    1,    2,    1
    } ;

static const flex_int16_t yy_base[469] =
    {   0,
        0,   68,   70,   75,    0,    0,  928,  929,  925,  929,
      929,  899,   68,  929,  898,   70,   77,  929,  929,  897,
       68,  929,   72,   89,   71,  119,  166,  899,  929,   59,
      895,   63,  929,    0,  107,  929,  929,  894,  860,   37,
       73,   47,   51,   77,  864,   73,  863,  875,   58,  860,
       66,  869,  146,  153,  137,  859,  864,  929,  131,  929,
      929,  199,  190,    0,  910,  929,  905,  882,  929,  907,
      929,  154,  929,  929,  127,  929,  929,  929,  197,  929,
      929,  141,  929,  929,  929,  929,  929,  929,  891,  222,
      199,  894,    0,  929,  204,  215,  262,    0,  192,  322,

      196,  181,  373,    0,  929,  879,  929,  929,  929,  878,
        0,  231,  250,  929,  845,  848,  856,  207,  859,  858,
      845,  214,  838,  839,  836,  836,  842,  838,  835,   87,
      832,    0,  212,  836,  837,  826,  835,  840,  222,  842,
      244,  842,  828,  182,  231,  832,  828,  830,  819,  822,
      270,  237,   96,  827,  929,  929,  297,  260,  261,  830,
      821,    0,  872,  867,  844,  436,  929,  235,  929,  437,
      929,  296,  378,  858,  289,    0,    0,  409,  285,  459,
        0,  519,  412,  414,    0,  448,    0,    0,  929,  588,
      466,    0,  168,    0,  419,  438,    0,  929,  929,  815,

      817,  826,  815,  820,  808,  806,  232,  821,  816,  818,
      814,  806,  812,  799,  814,    0,  809,  808,  798,  802,
        0,  803,  798,    0,  797,  791,  239,  788,  794,  793,
      794,  783,  788,  784,  786,  793,  779,  777,  777,  779,
      776,  787,  786,  776,  780,  779,  783,  785,  774,  778,
      780,    0,    0,  929,  639,  929,  354,    0,  457,    0,
      645,    0,  405,    0,  458,  635,  462,    0,    0,  679,
        0,    0,    0,    0,    0,  653,  469,    0,    0,    0,
      772,  767,    0,    0,  763,  761,  769,  758,  758,  764,
        0,    0,  758,  768,  754,    0,  758,    0,  757,  808,

      754,  752,  765,  747,  763,  758,  753,  750,  743,  743,
      748,  729,  731,  715,  714,  714,  709,  695,    0,    0,
      267,  676,  681,  676,    0,  668,  679,  674,  671,  929,
        0,    0,    0,    0,    0,    0,  471,    0,  482,    0,
      633,    0,  621,    0,  678,    0,    0,  667,  668,  673,
      672,  663,    0,  671,  669,  360,  667,  651,  650,  661,
      648,  662,  660,  648,  637,  640,    0,    0,  645,  638,
      640,  624,  633,  639,  633,  635,    0,  622,    0,  625,
        0,  609,  568,    0,    0,    0,    0,    0,  553,  544,
        0,    0,    0,    0,    0,  545,    0,  533,  532,    0,

      513,  485,    0,  472,  469,    0,    0,    0,    0,    0,
        0,  453,  459,  450,  456,  444,  431,  425,  417,    0,
      408,    0,  398,    0,  406,    0,  393,  397,    0,  396,
      368,  365,  929,  356,    0,  299,    0,  289,    0,    0,
        0,    0,    0,  929,  929,    0,  929,  731,  737,  743,
      749,  318,  755,  761,  767,  773,  779,  785,  787,  307,
      303,  793,  295,  243,  208,  188,  118,   77
    } ;

static const flex_int16_t yy_def[469] =
    {   0,
      447,    1,  448,  448,  449,  449,  447,  447,  447,  447,
      447,  447,  450,  447,  447,  447,  451,  447,  447,  447,
      447,  447,  447,  447,  447,  447,   26,  447,  447,  447,
      447,  447,  447,  452,  452,  447,  447,  447,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  447,  447,  447,
      447,  447,  447,  453,  447,  447,  454,  455,  447,  447,
      447,  450,  447,  447,  450,  447,  447,  447,  456,  447,
      447,  451,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  457,  458,  447,   90,   26,  459,  460,  461,  447,

      460,  460,  447,   27,  447,  447,  447,  447,  447,  447,
      452,  450,  451,  447,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  447,  447,  447,  447,  447,  447,
      447,  453,  447,  454,  455,  456,  447,  456,  447,  462,
      447,  447,  447,  457,  457,  458,   95,  460,  460,  459,
      463,  447,  463,  463,  460,  461,  464,  465,  447,  447,
      460,  466,  460,  460,  460,  103,  467,  447,  447,  452,

      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  447,
      447,  453,  453,  447,  447,  447,  460,  460,  460,  463,
      463,  468,  463,  463,  463,  464,  464,  464,  465,  465,
      465,  460,  466,  460,  460,  467,  467,  467,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,

      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  447,  447,  447,
      460,  460,  463,  468,  463,  463,  464,  464,  464,  465,
      467,  467,  467,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  447,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  447,  447,  464,  464,  467,  467,  452,  452,  452,
      452,  452,  452,  452,  452,  447,  452,  452,  452,  452,

      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  447,  447,  452,  452,
      447,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  447,  447,  452,  447,  452,  452,  452,  452,
      452,  452,  452,  447,  447,  452,    0,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447
    } ;

static const flex_int16_t yy_nxt[999] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       27,   27,   27,   28,   29,   30,   31,   32,   33,   34,
       34,   34,   34,   34,   35,   35,   34,   36,    8,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   34,   46,
       34,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   34,   34,   34,   58,   59,   60,   61,   62,
       73,   65,   66,   74,   63,   67,   65,   66,   77,   80,
       67,   84,  334,   92,  106,  107,   81,   86,   93,  109,
      110,  116,  122,  117,   85,   68,   78,   94,   87,   88,

       68,  123,  124,  136,  125,   89,   75,   90,   90,   90,
       90,   90,  112,  126,  118,   82,  113,  137,  127,  132,
       91,  119,  139,  278,  120,  140,  133,  121,  128,  447,
       72,  129,  217,  130,   91,   95,  218,   96,   96,   96,
       97,   97,  112,  447,   79,  247,  113,  248,   98,   99,
      100,   98,   98,  101,  102,  103,   73,  155,  151,   74,
       98,   99,   98,   98,  100,   98,   98,   98,   98,   98,
      101,   98,   98,   98,   98,   98,   98,   98,  102,   98,
       98,  103,   98,   98,  104,  104,  104,  104,  104,  142,
      152,  159,   75,  273,  143,  144,   98,  156,  147,   80,

      157,  148,   98,  274,  145,  158,  167,  146,   98,  149,
      186,  186,  172,  269,  172,  195,  150,  173,  173,  173,
      173,  173,  177,  177,  177,  177,  177,  274,   98,  235,
      193,  194,  195,   73,  160,  168,   74,  447,  166,  161,
       90,   90,   90,   90,   90,   98,  236,  193,  268,  178,
      179,   98,   80,  170,  171,  194,  171,   98,  203,   81,
      208,  159,  159,  220,  204,  209,  178,  170,  171,   75,
      221,  227,  237,  171,  179,  112,  228,   98,   95,  113,
      180,  180,  180,  180,  180,  230,  244,  238,   82,  286,
      287,  231,  304,  182,  245,  246,  183,  184,  157,  305,

      260,  175,  232,  158,  160,  160,  256,  182,  187,  161,
      161,  375,  185,  183,  173,  173,  173,  173,  173,  259,
      376,  184,  188,  111,  189,  188,  188,  188,  188,  188,
      188,  188,  188,  446,  188,  190,  259,  190,  188,  188,
      191,  191,  191,  191,  191,  188,  445,  188,  188,  188,
      188,  192,  192,  192,  192,  192,  192,  192,  192,  188,
      188,  356,  188,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  188,  188,  331,
      188,  196,  196,  196,  196,  196,  173,  173,  173,  173,

      173,  444,  196,  196,  196,  196,  197,  197,  197,  197,
      443,  396,  442,  331,  196,  196,  196,  196,  196,  196,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,   80,  189,
      335,  441,  440,  257,  258,  254,  263,  264,  265,  439,
      190,  438,  190,  275,  437,  255,  255,  255,  255,  255,
      257,  436,  435,  263,  335,  265,  186,  186,  258,  434,
      275,  264,  276,  277,  168,   95,  433,  180,  180,  180,
      180,  180,  266,  267,  191,  191,  191,  191,  191,  276,
      182,  332,  336,  183,  184,  432,  339,  277,  272,  266,

      272,  431,  430,  343,  182,  429,  384,  267,  332,  336,
      183,  428,  272,  339,  427,  426,  385,  272,  184,  188,
      343,  189,  188,  188,  188,  188,  188,  188,  188,  188,
      384,  188,  190,  385,  190,  188,  188,  261,  261,  261,
      261,  261,  188,  425,  188,  188,  188,  188,  262,  262,
      262,  262,  262,  262,  262,  262,  188,  188,  424,  188,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  188,  188,  423,  188,  188,  422,
      189,  188,  188,  188,  188,  188,  188,  188,  188,  421,

      188,  188,  420,  188,  188,  188,  270,  270,  270,  270,
      270,  188,  419,  188,  188,  188,  188,  271,  271,  271,
      271,  271,  271,  271,  271,  188,  188,  418,  188,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  188,  188,  387,  188,  255,  255,  255,
      255,  255,  417,  261,  261,  261,  261,  261,  386,  337,
      338,  330,  387,  330,  416,  415,  414,  333,  413,  333,
      412,  411,  410,  409,  408,  330,  337,  341,  342,  407,
      330,  333,  386,  406,  338,  405,  333,  270,  270,  270,

      270,  270,  404,  403,  341,  402,  401,  400,  399,  398,
      397,  340,  342,  340,  395,  394,  393,  392,  391,  390,
      389,  388,  383,  382,  381,  340,  380,  379,  378,  377,
      340,   64,   64,   64,   64,   64,   64,   69,   69,   69,
       69,   69,   69,   72,   72,   72,  374,   72,   72,   79,
       79,   79,  373,   79,   79,  162,  162,  372,  162,  162,
      162,  164,  164,  371,  164,  164,  164,  165,  165,  370,
      165,  165,  165,  166,  166,  166,  369,  166,  166,  174,
      174,  174,  174,  174,  174,  176,  176,  368,  176,  176,
      176,  181,  181,  188,  367,  188,  188,  188,  188,  366,

      365,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      355,  354,  353,  320,  352,  351,  350,  349,  348,  347,
      346,  345,  344,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  303,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  285,  284,  283,  282,  281,  280,  279,
      175,  253,  252,  163,  251,  250,  249,  243,  242,  241,
      240,  239,  234,  233,  229,  226,  225,  224,  223,  222,
      219,  216,  215,  214,  213,  212,  211,  210,  207,  206,

      205,  202,  201,  200,  199,  198,  175,  169,   70,  162,
      162,  163,  154,  153,  141,  138,  135,  134,  131,  115,
      114,  108,  105,   83,   76,   71,   70,  447,    7,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447

    } ;

static const flex_int16_t yy_chk[999] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
       13,    3,    3,   13,    2,    3,    4,    4,   16,   17,
        4,   21,  468,   25,   30,   30,   17,   23,   25,   32,
       32,   40,   42,   40,   21,    3,   16,   25,   23,   23,

        4,   42,   43,   49,   43,   24,   13,   24,   24,   24,
       24,   24,   35,   43,   41,   17,   35,   49,   44,   46,
       24,   41,   51,  467,   41,   51,   46,   41,   44,   75,
       75,   44,  130,   44,   24,   26,  130,   26,   26,   26,
       26,   26,   55,   82,   82,  153,   55,  153,   26,   26,
       26,   26,   26,   26,   26,   26,   72,   59,   55,   72,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   27,   27,   27,   27,   27,   53,
       55,   63,   72,  466,   53,   53,   27,   59,   54,   79,

       62,   54,   27,  193,   53,   62,   79,   53,   27,   54,
       99,   99,   91,  465,   91,  102,   54,   91,   91,   91,
       91,   91,   95,   95,   95,   95,   95,  193,   27,  144,
      101,  101,  102,  112,   63,   79,  112,  168,  168,   63,
       90,   90,   90,   90,   90,   96,  144,  101,  464,   96,
       96,   96,  113,   90,   90,  101,   90,   96,  118,  113,
      122,  158,  159,  133,  118,  122,   96,   90,   90,  112,
      133,  139,  145,   90,   96,  151,  139,   96,   97,  151,
       97,   97,   97,   97,   97,  141,  152,  145,  113,  207,
      207,  141,  227,   97,  152,  152,   97,   97,  157,  227,

      463,  175,  141,  157,  158,  159,  175,   97,  461,  158,
      159,  321,  460,   97,  172,  172,  172,  172,  172,  179,
      321,   97,  100,  452,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  438,  100,  100,  179,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  436,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  356,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  257,
      100,  103,  103,  103,  103,  103,  173,  173,  173,  173,

      173,  434,  103,  103,  103,  103,  103,  103,  103,  103,
      432,  356,  431,  257,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  166,  170,
      263,  430,  428,  178,  178,  166,  183,  183,  184,  427,
      170,  425,  170,  195,  423,  170,  170,  170,  170,  170,
      178,  421,  419,  183,  263,  184,  186,  186,  178,  418,
      195,  183,  196,  196,  166,  180,  417,  180,  180,  180,
      180,  180,  186,  186,  191,  191,  191,  191,  191,  196,
      180,  259,  265,  180,  180,  416,  267,  196,  191,  186,

      191,  415,  414,  277,  180,  413,  337,  186,  259,  265,
      180,  412,  191,  267,  405,  404,  339,  191,  180,  182,
      277,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      337,  182,  182,  339,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  402,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  401,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  399,  182,  190,  398,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  396,

      190,  190,  390,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  389,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  383,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  343,  190,  255,  255,  255,
      255,  255,  382,  261,  261,  261,  261,  261,  341,  266,
      266,  255,  343,  255,  380,  378,  376,  261,  375,  261,
      374,  373,  372,  371,  370,  255,  266,  276,  276,  369,
      255,  261,  341,  366,  266,  365,  261,  270,  270,  270,

      270,  270,  364,  363,  276,  362,  361,  360,  359,  358,
      357,  270,  276,  270,  355,  354,  352,  351,  350,  349,
      348,  345,  329,  328,  327,  270,  326,  324,  323,  322,
      270,  448,  448,  448,  448,  448,  448,  449,  449,  449,
      449,  449,  449,  450,  450,  450,  318,  450,  450,  451,
      451,  451,  317,  451,  451,  453,  453,  316,  453,  453,
      453,  454,  454,  315,  454,  454,  454,  455,  455,  314,
      455,  455,  455,  456,  456,  456,  313,  456,  456,  457,
      457,  457,  457,  457,  457,  458,  458,  312,  458,  458,
      458,  459,  459,  462,  311,  462,  462,  462,  462,  310,

      309,  308,  307,  306,  305,  304,  303,  302,  301,  300,
      299,  297,  295,  294,  293,  290,  289,  288,  287,  286,
      285,  282,  281,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  226,  225,  223,
      222,  220,  219,  218,  217,  215,  214,  213,  212,  211,
      210,  209,  208,  206,  205,  204,  203,  202,  201,  200,
      174,  165,  164,  163,  161,  160,  154,  150,  149,  148,
      147,  146,  143,  142,  140,  138,  137,  136,  135,  134,
      131,  129,  128,  127,  126,  125,  124,  123,  121,  120,

      119,  117,  116,  115,  110,  106,   92,   89,   70,   68,
       67,   65,   57,   56,   52,   50,   48,   47,   45,   39,
       38,   31,   28,   20,   15,   12,    9,    7,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447

    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[141] =
    {   0,
0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/lexer.l"
#line 2 "src/lexer.l"


#include <iostream>
#include <vector>
#include <map>
#include <string>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cctype>

using std::string;
using std::vector;
using std::map;
using std::cout;
using std::cerr;
using std::endl;


int currentLineNumber = 1;
int currentColumn = 1;

#define YY_USER_ACTION currentColumn += yyleng;


struct LexicalToken {
    string lexeme;
    string type;

    LexicalToken(const string& lex, const string& typ)
        : lexeme(lex), type(typ) {}
};

struct LexicalError {
    string message;
    int lineNumber;
    int column;

    LexicalError(const string& msg, int line, int col)
        : message(msg), lineNumber(line), column(col) {}
};

vector<LexicalToken> tokenList;
vector<LexicalError> errorList;

void addToken(const char* type, const char* lexeme) {
    tokenList.emplace_back(lexeme, type);
}

void addError(const char* lexeme, const char* category) {
    string errorMsg = "ERROR: " + string(category);
    errorList.emplace_back(errorMsg, currentLineNumber, currentColumn - (int)strlen(lexeme));
}

/* symbol table */
struct SymbolEntry {
    string name;
    int occurrences;
};

map<string, SymbolEntry> symbolTable;
map<string, int> keywordTable;

void addSymbol(const char* name) {
    string key(name);
    auto it = symbolTable.find(key);
    if (it != symbolTable.end()) {
        it->second.occurrences++;
    } else {
        symbolTable[key] = SymbolEntry{key, 1};
    }
}

void addKeyword(const char* name) {
    keywordTable[string(name)]++;
}

/* output */
void printAnalysisResults() {
    cout << "=================================================================" << endl;
    cout << "                    LEXICAL ANALYSIS TABLE" << endl;
    cout << "=================================================================" << endl;

    if (!errorList.empty()) {
        cout << "ERRORS FOUND:" << endl;
        cout << "-----------------------------------------------------------------" << endl;
        for (const auto& error : errorList) {
            cout << error.message << " at line " << error.lineNumber
                 << ", column " << error.column << endl;
        }
        cout << "-----------------------------------------------------------------" << endl << endl;
    } else {
        cout << "NO ERRORS FOUND" << endl;
        cout << "-----------------------------------------------------------------" << endl << endl;
    }

    cout << "VALID TOKENS:" << endl;
    printf("%-20s %s\n", "LEXEME", "TOKEN");
    cout << "-----------------------------------------------------------------" << endl;
    for (const auto& token : tokenList) {
        printf("%-20s %s\n", token.lexeme.c_str(), token.type.c_str());
    }
    cout << "-----------------------------------------------------------------" << endl;
    cout << "Total tokens found: " << tokenList.size() << endl;
    cout << "Total errors found: " << errorList.size() << endl;
    cout << "Total lines processed: " << currentLineNumber << endl;
}

void printSymbolTable() {
    cout << endl;
    cout << "=================================================================" << endl;
    cout << "                        SYMBOL TABLE" << endl;
    cout << "=================================================================" << endl;
    printf("%-20s %s\n", "IDENTIFIER", "OCCURRENCES");
    cout << "-----------------------------------------------------------------" << endl;
    for (const auto& pair : symbolTable) {
        printf("%-20s %d\n", pair.second.name.c_str(), pair.second.occurrences);
    }
    cout << "-----------------------------------------------------------------" << endl;
    cout << "Total unique identifiers: " << symbolTable.size() << endl;

    cout << endl;
    cout << "=================================================================" << endl;
    cout << "                        KEYWORD TABLE" << endl;
    cout << "=================================================================" << endl;
    printf("%-20s %s\n", "KEYWORD", "OCCURRENCES");
    cout << "-----------------------------------------------------------------" << endl;
    for (const auto& pair : keywordTable) {
        printf("%-20s %d\n", pair.first.c_str(), pair.second);
    }
    cout << "-----------------------------------------------------------------" << endl;
    cout << "Total unique keywords: " << keywordTable.size() << endl;
}
#line 982 "src/lex.yy.cc"

/* regex */
/* invalid number */
/* These now consume the whole malformed token (prefix of valid digits
   + the first bad character + any trailing alnum chars) instead of only
   matching when the very first digit after the base is already invalid.
   That's what makes them win flex's longest-match rule over
   INVALID_IDENTIFIER for things like 0b1021 or 0x1G. */
#line 991 "src/lex.yy.cc"

#define INITIAL 0
#define INCL 1
#define MULTILINE_COMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 202 "src/lexer.l"


#line 205 "src/lexer.l"
 /* preprocessor */
#line 1216 "src/lex.yy.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 448 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 929 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 206 "src/lexer.l"
{ addToken("PP_INCLUDE", yytext); BEGIN(INCL); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 207 "src/lexer.l"
; /* skip spaces between #include and the header name */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 208 "src/lexer.l"
{ addToken("HEADER_NAME", yytext); BEGIN(INITIAL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 209 "src/lexer.l"
{ addToken("HEADER_NAME", yytext); BEGIN(INITIAL); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 210 "src/lexer.l"
{ addError(yytext, "Malformed include directive"); BEGIN(INITIAL); }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 211 "src/lexer.l"
{ currentLineNumber++; currentColumn = 1; BEGIN(INITIAL); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 213 "src/lexer.l"
{ addToken("PP_DEFINE", yytext); }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 215 "src/lexer.l"
{ addError(yytext, "Unterminated comment");
                        char *p = yytext;
                        while (*p) {
                            if (*p == '\n') { currentLineNumber++; currentColumn = 1; }
                            p++;
                        }
                      }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 222 "src/lexer.l"
{ /* skip single-line comments */ }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 223 "src/lexer.l"
{
                        char *p = yytext;
                        while (*p) {
                            if (*p == '\n') { currentLineNumber++; currentColumn = 1; }
                            p++;
                        }
                      }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 231 "src/lexer.l"
{ currentLineNumber++; currentColumn = 1; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 232 "src/lexer.l"
{ /* skip whitespace */ }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 233 "src/lexer.l"
{ /* skip carriage return */ }
	YY_BREAK
/* keywords */
case 14:
YY_RULE_SETUP
#line 236 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 237 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 238 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 239 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 240 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 241 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 242 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 243 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 244 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 245 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 246 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 247 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 248 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 249 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 250 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 251 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 252 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 253 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 255 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 256 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 258 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 259 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 260 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 261 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 262 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 263 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 264 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 265 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 266 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 267 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 268 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 269 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 270 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 271 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 272 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 273 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 274 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 275 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 276 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 277 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 278 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 279 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 280 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 281 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 282 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 283 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 284 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 285 "src/lexer.l"
{ addToken("KEYWORD", yytext); addKeyword(yytext); }
	YY_BREAK
/* library functions */
case 62:
YY_RULE_SETUP
#line 288 "src/lexer.l"
{ addToken("PRINTF_FUNCTION", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 289 "src/lexer.l"
{ addToken("SCANF_FUNCTION", yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 290 "src/lexer.l"
{ addToken("MALLOC_FUNCTION", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 291 "src/lexer.l"
{ addToken("CALLOC_FUNCTION", yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 292 "src/lexer.l"
{ addToken("REALLOC_FUNCTION", yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 293 "src/lexer.l"
{ addToken("FREE_FUNCTION", yytext); }
	YY_BREAK
/* operators */
case 68:
YY_RULE_SETUP
#line 296 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 297 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 298 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 299 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 300 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 301 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 302 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 304 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 305 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 306 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 307 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 308 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 309 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 311 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 312 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 313 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 314 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 315 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 316 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 318 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 319 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 320 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 322 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 323 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 324 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 325 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 326 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 327 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 328 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 329 "src/lexer.l"
{ addToken("OPERATOR", yytext); }  /* also address-of / binary AND -> resolved by parser */
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 330 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 331 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 332 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
/* delimiters */
case 101:
YY_RULE_SETUP
#line 335 "src/lexer.l"
{ addToken("SEMICOLON", yytext); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 336 "src/lexer.l"
{ addToken("COMMA", yytext); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 337 "src/lexer.l"
{ addToken("LEFT_PAREN", yytext); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 338 "src/lexer.l"
{ addToken("RIGHT_PAREN", yytext); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 339 "src/lexer.l"
{ addToken("LEFT_BRACE", yytext); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 340 "src/lexer.l"
{ addToken("RIGHT_BRACE", yytext); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 341 "src/lexer.l"
{ addToken("LEFT_BRACKET", yytext); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 342 "src/lexer.l"
{ addToken("RIGHT_BRACKET", yytext); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 343 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 344 "src/lexer.l"
{ addToken("OPERATOR", yytext); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 345 "src/lexer.l"
{ addToken("COLON", yytext); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 346 "src/lexer.l"
{ addToken("QUESTION_MARK", yytext); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 347 "src/lexer.l"
{ addToken("HASH", yytext); }
	YY_BREAK
case 114:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 349 "src/lexer.l"
{ addError(yytext, "Unterminated string"); }
	YY_BREAK
case 115:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 350 "src/lexer.l"
{ addError(yytext, "Unterminated character"); }
	YY_BREAK
/* Invalid number formats */
case 116:
YY_RULE_SETUP
#line 353 "src/lexer.l"
{ addError(yytext, "Missing digits before exponent"); }
	YY_BREAK
case 117:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 354 "src/lexer.l"
{ addError(yytext, "Incomplete exponent"); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 355 "src/lexer.l"
{ addError(yytext, "Invalid exponent"); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 356 "src/lexer.l"
{ addError(yytext, "Incomplete exponent"); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 357 "src/lexer.l"
{ addError(yytext, "Invalid hex literal"); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 358 "src/lexer.l"
{ addError(yytext, "Invalid binary literal"); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 359 "src/lexer.l"
{ addError(yytext, "Invalid octal literal"); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 361 "src/lexer.l"
{ addToken("HEXADECIMAL_LITERAL", yytext); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 362 "src/lexer.l"
{ addToken("OCTAL_LITERAL", yytext); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 363 "src/lexer.l"
{ addToken("BINARY_LITERAL", yytext); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 364 "src/lexer.l"
{ addToken("EXPONENT_NUMBER_LITERAL", yytext); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 365 "src/lexer.l"
{ addToken("EXPONENT_NUMBER_LITERAL", yytext); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 366 "src/lexer.l"
{ addToken("INTEGER_LITERAL", yytext); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 367 "src/lexer.l"
{ addToken("FLOAT_LITERAL", yytext); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 368 "src/lexer.l"
{ addToken("BOOLEAN_LITERAL", yytext); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 369 "src/lexer.l"
{ addToken("STRING_LITERAL", yytext); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 370 "src/lexer.l"
{ addError(yytext, "Empty character literal"); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 371 "src/lexer.l"
{ addError(yytext, "Multi-character literal (only one character allowed)"); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 372 "src/lexer.l"
{ addToken("CHAR_LITERAL", yytext); }
	YY_BREAK
/* Identifiers */
case 135:
YY_RULE_SETUP
#line 375 "src/lexer.l"
{ addToken("IDENTIFIER", yytext); addSymbol(yytext); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 376 "src/lexer.l"
{ addToken("ELLIPSIS", yytext); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 377 "src/lexer.l"
{ addToken("DOT", yytext); }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 378 "src/lexer.l"
{ addError(yytext, "Invalid identifier"); }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 379 "src/lexer.l"
{ addError(yytext, "Unrecognized character"); }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 381 "src/lexer.l"
ECHO;
	YY_BREAK
#line 2015 "src/lex.yy.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(INCL):
case YY_STATE_EOF(MULTILINE_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 448 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 448 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 447);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 381 "src/lexer.l"


int main(int argc, char* argv[]) {
    bool showSymbolTables = false;
    vector<string> positional;

    for (int i = 1; i < argc; i++) {
        string arg = argv[i];
        if (arg == "--tables" || arg == "-t") {
            showSymbolTables = true;
        } else {
            positional.push_back(arg);
        }
    }

    if (positional.empty()) {
        cout << "Usage: " << argv[0] << " <input_file> [output_file] [--tables]" << endl;
        cout << "  input_file  : Source file to analyze" << endl;
        cout << "  output_file : Output file for results (optional, defaults to stdout)" << endl;
        cout << "  --tables    : Also print the symbol/keyword tables (optional; off by default" << endl;
        cout << "                so the default output is just the required token table)" << endl;
        cout << "Examples:" << endl;
        cout << "  " << argv[0] << " test.c" << endl;
        cout << "  " << argv[0] << " test.c output.txt" << endl;
        cout << "  " << argv[0] << " test.c output.txt --tables" << endl;
        return 1;
    }

    FILE* inputFile = fopen(positional[0].c_str(), "r");
    if (!inputFile) {
        cerr << "Error: Cannot open input file '" << positional[0] << "'" << endl;
        return 1;
    }
    yyin = inputFile;

    if (positional.size() >= 2) {
        const string& outputFileName = positional[1];
        if (!freopen(outputFileName.c_str(), "w", stdout)) {
            cerr << "Error: Cannot open output file '" << outputFileName << "'" << endl;
            fclose(inputFile);
            return 1;
        }
    }

    yylex();
    printAnalysisResults();
    if (showSymbolTables) {
        printSymbolTable();
    }

    fclose(inputFile);
    return errorList.empty() ? 0 : 1;
}
